# .github/workflows/ping-server.yml
name: Ping Server Every 10 Minutes

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes
  workflow_dispatch:       

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping the server and log response
        run: |
          echo "Pinging the server..."
          response=$(curl -s -w "%{http_code}" https://gresh-finance.onrender.com/ping)
          body=$(echo "$response" | sed '$d')
          status_code=$(echo "$response" | tail -n1)
          echo "Response body: $body"
          echo "HTTP status code: $status_code"

          if [ "$status_code" -ne 200 ]; then
            echo "Server did not respond with 200 OK!"
            exit 1
          fi
